ex1: clean
	gcc -o ex1 ex1.c

ex2: clean
	gcc -o ex2 ex2.c
	
ex3: clean
	gcc -o ex3 ex3.c

ex4: clean
	gcc -o ex4 ex4.c
	
ex5: clean
	gcc -o ex5 ex5.c
	
ex6: clean
	gcc -o ex6 ex6.c
	
ex7: clean
	gcc -o ex7 ex7.c
	
clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex7
	
all: ex1 ex2 ex3 ex4 ex5 ex6 ex7
